### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jaybdub**
Adds inline documentation to README for using jetson-io tool to configure pinmux for PWM sample.

### CODE REVIEW

**Comment by swarren** [comment]
Jetson-IO is a separate thing to Jetson.GPIO, so the README for GPIO shouldn't mention the other tools; they're already well documented in the main L4T documentation.

**Comment by jaybdub** [comment]
Hi Stephen,

This took a bit of hunting for me (and [others](https://github.com/NVIDIA/jetson-gpio/issues/37)).  

Are you open to directly linking to the documentation?  For example,

"You can find it in the [L4T Documentation -> Hardware Setup -> Configuring the 40 Pin Expansion Header](https://docs.nvidia.com/jetson/l4t/index.html#page/Tegra%2520Linux%2520Driver%2520Package%2520Development%2520Guide%2Fhw_setup_jetson_io.html%23)"

While it does seem thoroughly documented there, I do still feel having short inline steps here might help save some time for those who like to learn by example.

Anyways, loving this repo + jetson-io tool! 

Best,
John

**Comment by swarren** [comment]
To be honest, I would rather not provide a link to the L4T documentation; it as moved a few times and so keeping any link up-to-date would be rather problematic. The best approach would probably be to request that the L4T documentation be included as part of any L4T download rather than as a separate download; that way it'd always be available for access. The best place to request this would be the NVIDIA Jetson forums. Currently, the following link will work, but again that's moved a number of times too...
https://forums.developer.nvidia.com/c/agx-autonomous-machines/jetson-embedded-systems/70

**Comment by jaybdub** [comment]
Just FYI, In case you change your mind, I've modified the PR to just hyperlink the existing text to keep changes minimal.

Best,
John

**Comment by swarren** [comment]
I've pushed an alternate fix that doesn't rely on a URL that's so likely to change.

**Pull request closed without merging**
