### PR TITLE
Improved the model selecting mechanism for the docker containers

### PR DESCRIPTION
**Pull request by pjueon**
- Add `get_model()` function for docker containers. 
  - From the docker containers, `compatible_path` cannot be found unless you run them in privileged mode
  (related to the issue #52 )
  - To solve this, if `compatible_path` cannot be found, check the environment variable "JETSON_MODEL_NAME"
  - You can directly set the model info for the docker containers through the environment variable, without editing the source code.
- Add a sample Dockerfile
- Update the README

I'm not familiar with docker so the sample Dockerfile might need to be improved.

### CODE REVIEW

**Comment by pjueon** [comment]
Maybe non-root option is unnecessary.
In that case, entrypoint.sh can be removed.

**Comment by anhmiuhv** [comment]
I think you should put the docker file into samples folder. I think user should write their own dockerfile based on the Jetpack version they use

**Comment by pjueon** [comment]
Ok, I'll move the file when I get home.

**Comment by pjueon** [comment]
Alright, I moved it to `samples` directory.
And I also removed the non-root user example and simplify the Dockerfile and README.

**Comment by pjueon** [comment]
@anhmiuhv Could you review this again please?

**Pull request merged**
